"""Aadhaar card field schema."""
from securemask.schemas.base import FieldSchema

fields = [
    FieldSchema(
        field_name="aadhaar_number",
        sensitivity_weight=10,
        extraction_method="qr_primary_regex_fallback",
        regex_pattern=r"\b\d{4}\s?\d{4}\s?\d{4}\b",
        fuzzy_threshold=85,
        anchor_keywords=["aadhaar", "uid", "आधार", "unique"],
        zone="middle",
        always_redact=False,
    ),
    FieldSchema(
        field_name="name",
        sensitivity_weight=5,
        extraction_method="qr_primary_ner_fallback",
        regex_pattern=None,
        fuzzy_threshold=0,
        anchor_keywords=["name", "नाम"],
        zone="top",
        always_redact=False,
    ),
    FieldSchema(
        field_name="father_name",
        sensitivity_weight=4,
        extraction_method="qr_primary_ner_fallback",
        regex_pattern=None,
        fuzzy_threshold=0,
        anchor_keywords=["s/o", "d/o", "w/o", "father", "पिता"],
        zone="top",
        always_redact=False,
    ),
    FieldSchema(
        field_name="dob",
        sensitivity_weight=4,
        extraction_method="qr_primary_regex_fallback",
        # Relaxed regex: handles OCR concatenation like "DOB:15/04/2006" and "DOB: 15/04/2006"
        regex_pattern=r"(?:^|[\s:\/])(0?[1-9]|[12]\d|3[01])[\/\-\.\s](0?[1-9]|1[012])[\/\-\.\s](\d{4})(?:$|[\s,])",
        fuzzy_threshold=75,
        anchor_keywords=["dob", "date of birth", "जन्म तिथि", "जन्म तारीख",
                         "year of birth", "yob", "birth"],
        zone="anywhere",
        always_redact=False,
    ),
    FieldSchema(
        field_name="gender",
        sensitivity_weight=2,
        extraction_method="regex_fuzzy",
        regex_pattern=r"(?i)\b(male|female|transgender|पुरुष|महिला|पुरूष)\b",
        fuzzy_threshold=70,
        anchor_keywords=["gender", "sex", "लिंग"],
        zone="anywhere",
        always_redact=False,
    ),
    FieldSchema(
        field_name="address",
        sensitivity_weight=7,
        extraction_method="qr_primary_ner_fallback",
        regex_pattern=None,
        fuzzy_threshold=0,
        anchor_keywords=["address", "पता", "s/o", "w/o", "d/o",
                         "house", "village", "dist", "pin", "state",
                         "nagar", "road", "street", "colony"],
        zone="bottom",
        always_redact=False,
    ),
    FieldSchema(
        field_name="phone",
        sensitivity_weight=6,
        extraction_method="regex_fuzzy",
        regex_pattern=r"\b(\+91[\-\s]?)?[6-9]\d{9}\b",
        fuzzy_threshold=90,
        anchor_keywords=["mobile", "phone", "contact", "mo."],
        zone="anywhere",
        always_redact=False,
    ),
    FieldSchema(
        field_name="photo",
        sensitivity_weight=8,
        extraction_method="image",
        regex_pattern=None,
        fuzzy_threshold=0,
        anchor_keywords=[],
        zone="top",
        always_redact=True,
    ),
    FieldSchema(
        field_name="qr_code",
        sensitivity_weight=9,
        extraction_method="image",
        regex_pattern=None,
        fuzzy_threshold=0,
        anchor_keywords=[],
        zone="bottom",
        always_redact=True,
    ),
]
